// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bc.Models.DbModels;

#nullable disable

namespace bc.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250613113801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bc.Models.DbModels.Kategoria", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategorii");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("bc.Models.DbModels.Produkt", b =>
                {
                    b.Property<int>("IdProduktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduktu"));

                    b.Property<int?>("IdKategorii")
                        .HasColumnType("int");

                    b.Property<string>("NazwaProduktu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduktu");

                    b.HasIndex("IdKategorii");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("bc.Models.DbModels.Skladnik", b =>
                {
                    b.Property<int>("IdSkladnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkladnika"));

                    b.Property<string>("NazwaSkladnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSkladnika");

                    b.ToTable("Skladniki");
                });

            modelBuilder.Entity("bc.Models.DbModels.Zamowienie", b =>
                {
                    b.Property<int>("IdZamowienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZamowienia"));

                    b.Property<int>("StatusZamowienia")
                        .HasColumnType("int");

                    b.HasKey("IdZamowienia");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("bc.Models.DbModels.Produkt", b =>
                {
                    b.HasOne("bc.Models.DbModels.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("IdKategorii");

                    b.Navigation("Kategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
