// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bc.Models.DbModels;

#nullable disable

namespace bc.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250614195814_BazuniaKawiarni")]
    partial class BazuniaKawiarni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bc.Models.DbModels.Kategoria", b =>
                {
                    b.Property<int>("IdKategorii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKategorii"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKategorii");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            IdKategorii = 1,
                            Name = "Kawa"
                        },
                        new
                        {
                            IdKategorii = 2,
                            Name = "Herbata"
                        },
                        new
                        {
                            IdKategorii = 3,
                            Name = "Desery"
                        });
                });

            modelBuilder.Entity("bc.Models.DbModels.Produkt", b =>
                {
                    b.Property<int>("IdProduktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduktu"));

                    b.Property<int>("IdKategorii")
                        .HasColumnType("int");

                    b.Property<string>("NazwaProduktu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduktu");

                    b.HasIndex("IdKategorii");

                    b.ToTable("Produkty");

                    b.HasData(
                        new
                        {
                            IdProduktu = 1,
                            IdKategorii = 1,
                            NazwaProduktu = "Espresso"
                        },
                        new
                        {
                            IdProduktu = 2,
                            IdKategorii = 1,
                            NazwaProduktu = "Cappuccino"
                        },
                        new
                        {
                            IdProduktu = 3,
                            IdKategorii = 2,
                            NazwaProduktu = "Zielona herbata"
                        });
                });

            modelBuilder.Entity("bc.Models.DbModels.ProduktZamowienie", b =>
                {
                    b.Property<int>("PzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PzId"));

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("ZamowienieId")
                        .HasColumnType("int");

                    b.HasKey("PzId");

                    b.HasIndex("ProduktId");

                    b.HasIndex("ZamowienieId");

                    b.ToTable("ProduktyZamowienia");

                    b.HasData(
                        new
                        {
                            PzId = 1,
                            Ilosc = 2,
                            ProduktId = 1,
                            ZamowienieId = 1
                        },
                        new
                        {
                            PzId = 2,
                            Ilosc = 1,
                            ProduktId = 2,
                            ZamowienieId = 2
                        });
                });

            modelBuilder.Entity("bc.Models.DbModels.Skladnik", b =>
                {
                    b.Property<int>("IdSkladnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkladnika"));

                    b.Property<string>("NazwaSkladnika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSkladnika");

                    b.ToTable("Skladniki");

                    b.HasData(
                        new
                        {
                            IdSkladnika = 1,
                            NazwaSkladnika = "Mleko"
                        },
                        new
                        {
                            IdSkladnika = 2,
                            NazwaSkladnika = "Cukier"
                        },
                        new
                        {
                            IdSkladnika = 3,
                            NazwaSkladnika = "Cytryna"
                        });
                });

            modelBuilder.Entity("bc.Models.DbModels.Zamowienie", b =>
                {
                    b.Property<int>("IdZamowienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZamowienia"));

                    b.Property<DateTime>("DataZamowienia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KwotaZamowienia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusZamowienia")
                        .HasColumnType("int");

                    b.HasKey("IdZamowienia");

                    b.ToTable("Zamowienia");

                    b.HasData(
                        new
                        {
                            IdZamowienia = 1,
                            DataZamowienia = new DateTime(2023, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            KwotaZamowienia = 15.99m,
                            StatusZamowienia = 0
                        },
                        new
                        {
                            IdZamowienia = 2,
                            DataZamowienia = new DateTime(2023, 1, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            KwotaZamowienia = 25.50m,
                            StatusZamowienia = 1
                        });
                });

            modelBuilder.Entity("bc.Models.DbModels.Produkt", b =>
                {
                    b.HasOne("bc.Models.DbModels.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("IdKategorii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });

            modelBuilder.Entity("bc.Models.DbModels.ProduktZamowienie", b =>
                {
                    b.HasOne("bc.Models.DbModels.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bc.Models.DbModels.Zamowienie", "Zamowienie")
                        .WithMany()
                        .HasForeignKey("ZamowienieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");

                    b.Navigation("Zamowienie");
                });
#pragma warning restore 612, 618
        }
    }
}
